### ISSUE TITLE
color scheme for main entities

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/iad#5]
Provide a good looking color scheme for Iad's main entities Site, ArchEnt, ResearchEvent and MonumentProtection. See  [iad.archiv.styles](https://github.com/acdh-oeaw/iad/commit/d59047e148003d6dd6734bbb605012f317969f5d) on how to define the colors...

Those colors will/should be used for 
* the polygons
* the class specific browsing/detail views. 

Ideally a user then immediately recognizes the class type by the color

**Comment by csae8092** [comment]
colors defined in `webpage\static\webpage\css\style.css`
```css
.site-page {
    background-color: #F18C8E;
    color: white;
}
.archent-page {
    background-color: #F0B7A4;
    color: white;
}
.researchevent-page {
    background-color: #F1D1B5;
    color: white;
}
.monumentprotection-page {
    background-color: #568EA6;
    color: white;
}
```
